### PR TITLE
Feature/http basic auth

### PR DESCRIPTION
**Pull request by merrickluo**
check and add proxy basic authorization info before connect

### CODE REVIEW

**Comment by wfjsw** [comment]
Seems Gradle Sync takes more time than usual, will try again tomorrow.

**Comment by wfjsw** [comment]
```
00:47:15.844 [ERROR] [system.err] process_begin: CreateProcess(NULL, D:/Android/android-sdk/ndk-bundle/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-gcc-ar crsD ...[scrubbed].../sha512-armv4.o, ...) failed.
```

Working on it

**Comment by merrickluo** [comment]
https://github.com/merrickluo/SmartProxy/blob/master/app/build.gradle#L31-L40
try to remove these lines, this is for Android Studio ndk debugging, since it's not working anyway.

**Comment by wfjsw** [comment]
Did not solve the problem. I think something is wrong in Makefile.

**Comment by wfjsw** [comment]
I found the problem... the command line are too long to run on Windows.
Solved by prebuilding it in MSYS bash.

**Comment by wfjsw** [comment]
Proxy connection established, but it seems tunnels are not used and connections are made directly.

Screenshot

**Comment by wfjsw** [comment]
737a7a65f7806dabbb2441b72e36f483b1d4dff1 accounts for this bug. Please revert it.

**Comment by merrickluo** [comment]
@wfjsw looks like there is a 4 byte difference between Android 4.4 and above, I will look into that.

**Comment by merrickluo** [comment]
Fixed in https://github.com/merrickluo/SmartProxy/pull/12/commits/07418d0fd844f4c2cc76c59a25da764401dcd210 merge now

**Pull request merged**
